# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libppl-dev
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        # Install igakit and geomdl
        pip install https://github.com/dalcinl/igakit/archive/refs/heads/master.zip --no-cache-dir
        SETUPTOOLS_USE_CYTHON=1 pip install git+https://github.com/orbingol/NURBS-Python.git --no-cache-dir
        # Install torch and libtorch
        pip install torch==2.8.0 --index-url https://download.pytorch.org/whl/cpu --no-cache-dir
        curl -LO https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.8.0%2Bcpu.zip
        unzip -q libtorch-shared-with-deps-2.8.0%2Bcpu.zip
        # Install torchTT
        pip install git+https://github.com/ion-g-ion/torchTT
        # Set environment variables for ttnte install
        export TORCH_INSTALL_PREFIX=$(pwd)/libtorch
        export _GLIBCXX_USE_CXX11_ABI=$(python3 -c "import torch; print(int(torch._C._GLIBCXX_USE_CXX11_ABI))")
        # Install ttnte
        TTNTE_CPP_BACKEND=1 USE_CUDA=0 pip install . -v
    - name: Lint with flake8
      run: |
        cd ttnte
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --exclude archive --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --exclude archive --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd tests
        pytest unit/*
        TTNTE_CPP_BACKEND=0 pytest regression/*
        TTNTE_CPP_BACKEND=1 pytest regression/*
